[package]
name = "openlcd-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.36"
ab_glyph = "0.2"

openlcd-core = { path = "../openlcd-core" }
openlcd-driver = { path = "../openlcd-driver" }
openlcd-fake-driver = { path = "../openlcd-fake-driver" }
openlcd-render = { path = "../openlcd-render" }
openlcd-theme = { path = "../openlcd-theme" }

thiserror = "2"
rfd = "0.17.2"
